async:
  executor:
    thread:
      core_pool_size : 1
      max_pool_size : 2
      queue_capacity : 20
      keepAlive : 30
      name_prefix : firebase-push

# 端口号8080
server:
  port: 8080

# 数据库名：mysql，用户名root，密码123456
spring:
  datasource:
#    username: root
#    password: Ztan05022317a
#    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ssports_tech
    password: Qwer1234%
    url: jdbc:mysql://ssports-public.mysql.polardb.rds.aliyuncs.com:3306/ssports_shop



# mybatis-plus配置
mybatis-plus:
  # xml文件位置
  mapper-locations: classpath:mapper/*.xml
